use_frameworks!

platform :ios, '9.0'

target 'BreakPadExt_Example' do
  pod 'BreakPadExt', :path => '../'

  target 'BreakPadExt_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
