# use_frameworks!

platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/ItghostFan/Specs.git'

install! 'cocoapods',
  :generate_multiple_pod_projects => true

target 'BreakPadExt_Example' do
  pod 'BreakPadExtAbi/Dylib'
#  pod 'BreakPadExt', :path => '../'
  pod 'ReactiveObjC'
  pod 'Masonry'

  target 'BreakPadExtTests' do
    inherit! :search_paths
  end
  target 'BreakPadExtUITests' do
    inherit! :search_paths
  end
end
