//
//  BreakPadExtController.h
//  BreakPadExt
//
//  Created by ItghostFan on 2022/3/9.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface BreakPadExtController : NSObject

#pragma mark - BreakpadController

// Starts the BreakpadController by registering crash handlers. If
// |onCurrentThread| is YES, all setup is done on the current thread, otherwise
// it is done on a private queue.
- (void)start:(BOOL)onCurrentThread;

// Unregisters the crash handlers.
- (void)stop;

// Update the controller configuration. Merges its old configuration with the
// new one. Merge is done by replacing the old values by the new values.
- (void)updateConfiguration:(NSDictionary*)configuration;

@end

#pragma mark - Breakpad

#ifdef __cplusplus
extern "C" {
#endif

BOOL IsDebuggerActive();

#ifdef __cplusplus
}
#endif

#pragma mark - Breakpad Macros

/**
 @see BreakpadController.updateConfiguration
 // Specify some special keys to be used in the configuration file that is
 // generated by Breakpad and consumed by the crash_sender.
 */
#define BREAKPAD_VENDOR                "BreakpadVendor"
#define BREAKPAD_URL                   "BreakpadURL"
#define BREAKPAD_DUMP_DIRECTORY        "BreakpadMinidumpLocation"

#define IGNORE_DEBUGGER "BREAKPAD_IGNORE_DEBUGGER"

NS_ASSUME_NONNULL_END
